// Protocol version 1 between beancount and an Importer. A new optional field
// stays within v1; a new directive kind needs v2 (docs/adr/0001).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: importer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path of the Statement.
	StatementPath string `protobuf:"bytes,1,opt,name=statement_path,json=statementPath,proto3" json:"statement_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyRequest) Reset() {
	*x = IdentifyRequest{}
	mi := &file_importer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyRequest) ProtoMessage() {}

func (x *IdentifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyRequest.ProtoReflect.Descriptor instead.
func (*IdentifyRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{0}
}

func (x *IdentifyRequest) GetStatementPath() string {
	if x != nil {
		return x.StatementPath
	}
	return ""
}

type IdentifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       bool                   `protobuf:"varint,1,opt,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifyResponse) Reset() {
	*x = IdentifyResponse{}
	mi := &file_importer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyResponse) ProtoMessage() {}

func (x *IdentifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyResponse.ProtoReflect.Descriptor instead.
func (*IdentifyResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{1}
}

func (x *IdentifyResponse) GetMatches() bool {
	if x != nil {
		return x.Matches
	}
	return false
}

type ExtractRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path of the Statement.
	StatementPath string `protobuf:"bytes,1,opt,name=statement_path,json=statementPath,proto3" json:"statement_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_importer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractRequest) GetStatementPath() string {
	if x != nil {
		return x.StatementPath
	}
	return ""
}

type ExtractResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// In the order the Importer returned them.
	Directives    []*Directive `protobuf:"bytes,1,rep,name=directives,proto3" json:"directives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_importer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractResponse) GetDirectives() []*Directive {
	if x != nil {
		return x.Directives
	}
	return nil
}

type Directive struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Directive_Transaction
	//	*Directive_Balance
	Kind          isDirective_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directive) Reset() {
	*x = Directive{}
	mi := &file_importer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directive) ProtoMessage() {}

func (x *Directive) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directive.ProtoReflect.Descriptor instead.
func (*Directive) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{4}
}

func (x *Directive) GetKind() isDirective_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Directive) GetTransaction() *Transaction {
	if x != nil {
		if x, ok := x.Kind.(*Directive_Transaction); ok {
			return x.Transaction
		}
	}
	return nil
}

func (x *Directive) GetBalance() *Balance {
	if x != nil {
		if x, ok := x.Kind.(*Directive_Balance); ok {
			return x.Balance
		}
	}
	return nil
}

type isDirective_Kind interface {
	isDirective_Kind()
}

type Directive_Transaction struct {
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof"`
}

type Directive_Balance struct {
	Balance *Balance `protobuf:"bytes,2,opt,name=balance,proto3,oneof"`
}

func (*Directive_Transaction) isDirective_Kind() {}

func (*Directive_Balance) isDirective_Kind() {}

type Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_importer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{5}
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Date) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

// Amount is a decimal number in text, keeping the precision it was written
// with, and a currency. Either may be empty where Beancount lets it be missing.
type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_importer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{6}
}

func (x *Amount) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Amount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Transaction struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Date      *Date                  `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Flag      string                 `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Payee     *string                `protobuf:"bytes,3,opt,name=payee,proto3,oneof" json:"payee,omitempty"`
	Narration string                 `protobuf:"bytes,4,opt,name=narration,proto3" json:"narration,omitempty"`
	Tags      []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Links     []string               `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	Metadata  []*Metadata            `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty"`
	Postings  []*Posting             `protobuf:"bytes,8,rep,name=postings,proto3" json:"postings,omitempty"`
	// The bank's own identifier, written to the transaction's import-id
	// metadata. Empty when the Statement has none.
	ImportId      string `protobuf:"bytes,9,opt,name=import_id,json=importId,proto3" json:"import_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_importer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{7}
}

func (x *Transaction) GetDate() *Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Transaction) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *Transaction) GetPayee() string {
	if x != nil && x.Payee != nil {
		return *x.Payee
	}
	return ""
}

func (x *Transaction) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

func (x *Transaction) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Transaction) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Transaction) GetMetadata() []*Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Transaction) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *Transaction) GetImportId() string {
	if x != nil {
		return x.ImportId
	}
	return ""
}

type Posting struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Flag    string                 `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Account string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	// Unset when Booking interpolates it.
	Units         *Amount     `protobuf:"bytes,3,opt,name=units,proto3" json:"units,omitempty"`
	Cost          *Cost       `protobuf:"bytes,4,opt,name=cost,proto3" json:"cost,omitempty"`
	Price         *Price      `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Metadata      []*Metadata `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posting) Reset() {
	*x = Posting{}
	mi := &file_importer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posting) ProtoMessage() {}

func (x *Posting) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posting.ProtoReflect.Descriptor instead.
func (*Posting) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{8}
}

func (x *Posting) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *Posting) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Posting) GetUnits() *Amount {
	if x != nil {
		return x.Units
	}
	return nil
}

func (x *Posting) GetCost() *Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Posting) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Posting) GetMetadata() []*Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Cost is a cost specification as written, which may be incomplete: {} and
// {*} set no amount.
type Cost struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Merge bool                   `protobuf:"varint,1,opt,name=merge,proto3" json:"merge,omitempty"`
	// Written with double braces: amount is the total cost.
	Total  bool    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Amount *Amount `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// The total component after '#' in a compound cost.
	CompoundTotal *Amount `protobuf:"bytes,4,opt,name=compound_total,json=compoundTotal,proto3" json:"compound_total,omitempty"`
	Date          *Date   `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Label         string  `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cost) Reset() {
	*x = Cost{}
	mi := &file_importer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cost) ProtoMessage() {}

func (x *Cost) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cost.ProtoReflect.Descriptor instead.
func (*Cost) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{9}
}

func (x *Cost) GetMerge() bool {
	if x != nil {
		return x.Merge
	}
	return false
}

func (x *Cost) GetTotal() bool {
	if x != nil {
		return x.Total
	}
	return false
}

func (x *Cost) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Cost) GetCompoundTotal() *Amount {
	if x != nil {
		return x.CompoundTotal
	}
	return nil
}

func (x *Cost) GetDate() *Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Cost) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Price struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Amount *Amount                `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Written with @@: amount is the total price.
	Total         bool `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_importer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{10}
}

func (x *Price) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Price) GetTotal() bool {
	if x != nil {
		return x.Total
	}
	return false
}

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *Date                  `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Amount        *Amount                `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Tolerance     *Amount                `protobuf:"bytes,4,opt,name=tolerance,proto3" json:"tolerance,omitempty"`
	Metadata      []*Metadata            `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_importer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{11}
}

func (x *Balance) GetDate() *Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Balance) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Balance) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Balance) GetTolerance() *Amount {
	if x != nil {
		return x.Tolerance
	}
	return nil
}

func (x *Balance) GetMetadata() []*Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Unset for a key without a value.
	Value         *MetadataValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_importer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{12}
}

func (x *Metadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metadata) GetValue() *MetadataValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type MetadataValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*MetadataValue_String_
	//	*MetadataValue_Date
	//	*MetadataValue_Account
	//	*MetadataValue_Currency
	//	*MetadataValue_Tag
	//	*MetadataValue_Link
	//	*MetadataValue_Number
	//	*MetadataValue_Amount
	//	*MetadataValue_Boolean
	Kind          isMetadataValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataValue) Reset() {
	*x = MetadataValue{}
	mi := &file_importer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValue) ProtoMessage() {}

func (x *MetadataValue) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValue.ProtoReflect.Descriptor instead.
func (*MetadataValue) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{13}
}

func (x *MetadataValue) GetKind() isMetadataValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *MetadataValue) GetString_() string {
	if x != nil {
		if x, ok := x.Kind.(*MetadataValue_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *MetadataValue) GetDate() *Date {
	if x != nil {
		if x, ok := x.Kind.(*MetadataValue_Date); ok {
			return x.Date
		}
	}
	return nil
}

func (x *MetadataValue) GetAccount() string {
	if x != nil {
		if x, ok := x.Kind.(*MetadataValue_Account); ok {
			return x.Account
		}
	}
	return ""
}

func (x *MetadataValue) GetCurrency() string {
	if x != nil {
		if x, ok := x.Kind.(*MetadataValue_Currency); ok {
			return x.Currency
		}
	}
	return ""
}

func (x *MetadataValue) GetTag() string {
	if x != nil {
		if x, ok := x.Kind.(*MetadataValue_Tag); ok {
			return x.Tag
		}
	}
	return ""
}

func (x *MetadataValue) GetLink() string {
	if x != nil {
		if x, ok := x.Kind.(*MetadataValue_Link); ok {
			return x.Link
		}
	}
	return ""
}

func (x *MetadataValue) GetNumber() string {
	if x != nil {
		if x, ok := x.Kind.(*MetadataValue_Number); ok {
			return x.Number
		}
	}
	return ""
}

func (x *MetadataValue) GetAmount() *Amount {
	if x != nil {
		if x, ok := x.Kind.(*MetadataValue_Amount); ok {
			return x.Amount
		}
	}
	return nil
}

func (x *MetadataValue) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Kind.(*MetadataValue_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

type isMetadataValue_Kind interface {
	isMetadataValue_Kind()
}

type MetadataValue_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type MetadataValue_Date struct {
	Date *Date `protobuf:"bytes,2,opt,name=date,proto3,oneof"`
}

type MetadataValue_Account struct {
	Account string `protobuf:"bytes,3,opt,name=account,proto3,oneof"`
}

type MetadataValue_Currency struct {
	Currency string `protobuf:"bytes,4,opt,name=currency,proto3,oneof"`
}

type MetadataValue_Tag struct {
	Tag string `protobuf:"bytes,5,opt,name=tag,proto3,oneof"`
}

type MetadataValue_Link struct {
	Link string `protobuf:"bytes,6,opt,name=link,proto3,oneof"`
}

type MetadataValue_Number struct {
	Number string `protobuf:"bytes,7,opt,name=number,proto3,oneof"`
}

type MetadataValue_Amount struct {
	Amount *Amount `protobuf:"bytes,8,opt,name=amount,proto3,oneof"`
}

type MetadataValue_Boolean struct {
	Boolean bool `protobuf:"varint,9,opt,name=boolean,proto3,oneof"`
}

func (*MetadataValue_String_) isMetadataValue_Kind() {}

func (*MetadataValue_Date) isMetadataValue_Kind() {}

func (*MetadataValue_Account) isMetadataValue_Kind() {}

func (*MetadataValue_Currency) isMetadataValue_Kind() {}

func (*MetadataValue_Tag) isMetadataValue_Kind() {}

func (*MetadataValue_Link) isMetadataValue_Kind() {}

func (*MetadataValue_Number) isMetadataValue_Kind() {}

func (*MetadataValue_Amount) isMetadataValue_Kind() {}

func (*MetadataValue_Boolean) isMetadataValue_Kind() {}

var File_importer_proto protoreflect.FileDescriptor

const file_importer_proto_rawDesc = "" +
	"\n" +
	"\x0eimporter.proto\x12\x15beancount.importer.v1\"8\n" +
	"\x0fIdentifyRequest\x12%\n" +
	"\x0estatement_path\x18\x01 \x01(\tR\rstatementPath\",\n" +
	"\x10IdentifyResponse\x12\x18\n" +
	"\amatches\x18\x01 \x01(\bR\amatches\"7\n" +
	"\x0eExtractRequest\x12%\n" +
	"\x0estatement_path\x18\x01 \x01(\tR\rstatementPath\"S\n" +
	"\x0fExtractResponse\x12@\n" +
	"\n" +
	"directives\x18\x01 \x03(\v2 .beancount.importer.v1.DirectiveR\n" +
	"directives\"\x97\x01\n" +
	"\tDirective\x12F\n" +
	"\vtransaction\x18\x01 \x01(\v2\".beancount.importer.v1.TransactionH\x00R\vtransaction\x12:\n" +
	"\abalance\x18\x02 \x01(\v2\x1e.beancount.importer.v1.BalanceH\x00R\abalanceB\x06\n" +
	"\x04kind\"B\n" +
	"\x04Date\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03day\"<\n" +
	"\x06Amount\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xd5\x02\n" +
	"\vTransaction\x12/\n" +
	"\x04date\x18\x01 \x01(\v2\x1b.beancount.importer.v1.DateR\x04date\x12\x12\n" +
	"\x04flag\x18\x02 \x01(\tR\x04flag\x12\x19\n" +
	"\x05payee\x18\x03 \x01(\tH\x00R\x05payee\x88\x01\x01\x12\x1c\n" +
	"\tnarration\x18\x04 \x01(\tR\tnarration\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x14\n" +
	"\x05links\x18\x06 \x03(\tR\x05links\x12;\n" +
	"\bmetadata\x18\a \x03(\v2\x1f.beancount.importer.v1.MetadataR\bmetadata\x12:\n" +
	"\bpostings\x18\b \x03(\v2\x1e.beancount.importer.v1.PostingR\bpostings\x12\x1b\n" +
	"\timport_id\x18\t \x01(\tR\bimportIdB\b\n" +
	"\x06_payee\"\x8e\x02\n" +
	"\aPosting\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\tR\x04flag\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x123\n" +
	"\x05units\x18\x03 \x01(\v2\x1d.beancount.importer.v1.AmountR\x05units\x12/\n" +
	"\x04cost\x18\x04 \x01(\v2\x1b.beancount.importer.v1.CostR\x04cost\x122\n" +
	"\x05price\x18\x05 \x01(\v2\x1c.beancount.importer.v1.PriceR\x05price\x12;\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1f.beancount.importer.v1.MetadataR\bmetadata\"\xf6\x01\n" +
	"\x04Cost\x12\x14\n" +
	"\x05merge\x18\x01 \x01(\bR\x05merge\x12\x14\n" +
	"\x05total\x18\x02 \x01(\bR\x05total\x125\n" +
	"\x06amount\x18\x03 \x01(\v2\x1d.beancount.importer.v1.AmountR\x06amount\x12D\n" +
	"\x0ecompound_total\x18\x04 \x01(\v2\x1d.beancount.importer.v1.AmountR\rcompoundTotal\x12/\n" +
	"\x04date\x18\x05 \x01(\v2\x1b.beancount.importer.v1.DateR\x04date\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\"T\n" +
	"\x05Price\x125\n" +
	"\x06amount\x18\x01 \x01(\v2\x1d.beancount.importer.v1.AmountR\x06amount\x12\x14\n" +
	"\x05total\x18\x02 \x01(\bR\x05total\"\x85\x02\n" +
	"\aBalance\x12/\n" +
	"\x04date\x18\x01 \x01(\v2\x1b.beancount.importer.v1.DateR\x04date\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x125\n" +
	"\x06amount\x18\x03 \x01(\v2\x1d.beancount.importer.v1.AmountR\x06amount\x12;\n" +
	"\ttolerance\x18\x04 \x01(\v2\x1d.beancount.importer.v1.AmountR\ttolerance\x12;\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1f.beancount.importer.v1.MetadataR\bmetadata\"X\n" +
	"\bMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.beancount.importer.v1.MetadataValueR\x05value\"\xb7\x02\n" +
	"\rMetadataValue\x12\x18\n" +
	"\x06string\x18\x01 \x01(\tH\x00R\x06string\x121\n" +
	"\x04date\x18\x02 \x01(\v2\x1b.beancount.importer.v1.DateH\x00R\x04date\x12\x1a\n" +
	"\aaccount\x18\x03 \x01(\tH\x00R\aaccount\x12\x1c\n" +
	"\bcurrency\x18\x04 \x01(\tH\x00R\bcurrency\x12\x12\n" +
	"\x03tag\x18\x05 \x01(\tH\x00R\x03tag\x12\x14\n" +
	"\x04link\x18\x06 \x01(\tH\x00R\x04link\x12\x18\n" +
	"\x06number\x18\a \x01(\tH\x00R\x06number\x127\n" +
	"\x06amount\x18\b \x01(\v2\x1d.beancount.importer.v1.AmountH\x00R\x06amount\x12\x1a\n" +
	"\aboolean\x18\t \x01(\bH\x00R\abooleanB\x06\n" +
	"\x04kind2\xc1\x01\n" +
	"\bImporter\x12[\n" +
	"\bIdentify\x12&.beancount.importer.v1.IdentifyRequest\x1a'.beancount.importer.v1.IdentifyResponse\x12X\n" +
	"\aExtract\x12%.beancount.importer.v1.ExtractRequest\x1a&.beancount.importer.v1.ExtractResponseB:Z8github.com/robinvdvleuten/beancount/importer/internal/pbb\x06proto3"

var (
	file_importer_proto_rawDescOnce sync.Once
	file_importer_proto_rawDescData []byte
)

func file_importer_proto_rawDescGZIP() []byte {
	file_importer_proto_rawDescOnce.Do(func() {
		file_importer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_importer_proto_rawDesc), len(file_importer_proto_rawDesc)))
	})
	return file_importer_proto_rawDescData
}

var file_importer_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_importer_proto_goTypes = []any{
	(*IdentifyRequest)(nil),  // 0: beancount.importer.v1.IdentifyRequest
	(*IdentifyResponse)(nil), // 1: beancount.importer.v1.IdentifyResponse
	(*ExtractRequest)(nil),   // 2: beancount.importer.v1.ExtractRequest
	(*ExtractResponse)(nil),  // 3: beancount.importer.v1.ExtractResponse
	(*Directive)(nil),        // 4: beancount.importer.v1.Directive
	(*Date)(nil),             // 5: beancount.importer.v1.Date
	(*Amount)(nil),           // 6: beancount.importer.v1.Amount
	(*Transaction)(nil),      // 7: beancount.importer.v1.Transaction
	(*Posting)(nil),          // 8: beancount.importer.v1.Posting
	(*Cost)(nil),             // 9: beancount.importer.v1.Cost
	(*Price)(nil),            // 10: beancount.importer.v1.Price
	(*Balance)(nil),          // 11: beancount.importer.v1.Balance
	(*Metadata)(nil),         // 12: beancount.importer.v1.Metadata
	(*MetadataValue)(nil),    // 13: beancount.importer.v1.MetadataValue
}
var file_importer_proto_depIdxs = []int32{
	4,  // 0: beancount.importer.v1.ExtractResponse.directives:type_name -> beancount.importer.v1.Directive
	7,  // 1: beancount.importer.v1.Directive.transaction:type_name -> beancount.importer.v1.Transaction
	11, // 2: beancount.importer.v1.Directive.balance:type_name -> beancount.importer.v1.Balance
	5,  // 3: beancount.importer.v1.Transaction.date:type_name -> beancount.importer.v1.Date
	12, // 4: beancount.importer.v1.Transaction.metadata:type_name -> beancount.importer.v1.Metadata
	8,  // 5: beancount.importer.v1.Transaction.postings:type_name -> beancount.importer.v1.Posting
	6,  // 6: beancount.importer.v1.Posting.units:type_name -> beancount.importer.v1.Amount
	9,  // 7: beancount.importer.v1.Posting.cost:type_name -> beancount.importer.v1.Cost
	10, // 8: beancount.importer.v1.Posting.price:type_name -> beancount.importer.v1.Price
	12, // 9: beancount.importer.v1.Posting.metadata:type_name -> beancount.importer.v1.Metadata
	6,  // 10: beancount.importer.v1.Cost.amount:type_name -> beancount.importer.v1.Amount
	6,  // 11: beancount.importer.v1.Cost.compound_total:type_name -> beancount.importer.v1.Amount
	5,  // 12: beancount.importer.v1.Cost.date:type_name -> beancount.importer.v1.Date
	6,  // 13: beancount.importer.v1.Price.amount:type_name -> beancount.importer.v1.Amount
	5,  // 14: beancount.importer.v1.Balance.date:type_name -> beancount.importer.v1.Date
	6,  // 15: beancount.importer.v1.Balance.amount:type_name -> beancount.importer.v1.Amount
	6,  // 16: beancount.importer.v1.Balance.tolerance:type_name -> beancount.importer.v1.Amount
	12, // 17: beancount.importer.v1.Balance.metadata:type_name -> beancount.importer.v1.Metadata
	13, // 18: beancount.importer.v1.Metadata.value:type_name -> beancount.importer.v1.MetadataValue
	5,  // 19: beancount.importer.v1.MetadataValue.date:type_name -> beancount.importer.v1.Date
	6,  // 20: beancount.importer.v1.MetadataValue.amount:type_name -> beancount.importer.v1.Amount
	0,  // 21: beancount.importer.v1.Importer.Identify:input_type -> beancount.importer.v1.IdentifyRequest
	2,  // 22: beancount.importer.v1.Importer.Extract:input_type -> beancount.importer.v1.ExtractRequest
	1,  // 23: beancount.importer.v1.Importer.Identify:output_type -> beancount.importer.v1.IdentifyResponse
	3,  // 24: beancount.importer.v1.Importer.Extract:output_type -> beancount.importer.v1.ExtractResponse
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_importer_proto_init() }
func file_importer_proto_init() {
	if File_importer_proto != nil {
		return
	}
	file_importer_proto_msgTypes[4].OneofWrappers = []any{
		(*Directive_Transaction)(nil),
		(*Directive_Balance)(nil),
	}
	file_importer_proto_msgTypes[7].OneofWrappers = []any{}
	file_importer_proto_msgTypes[13].OneofWrappers = []any{
		(*MetadataValue_String_)(nil),
		(*MetadataValue_Date)(nil),
		(*MetadataValue_Account)(nil),
		(*MetadataValue_Currency)(nil),
		(*MetadataValue_Tag)(nil),
		(*MetadataValue_Link)(nil),
		(*MetadataValue_Number)(nil),
		(*MetadataValue_Amount)(nil),
		(*MetadataValue_Boolean)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_importer_proto_rawDesc), len(file_importer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_importer_proto_goTypes,
		DependencyIndexes: file_importer_proto_depIdxs,
		MessageInfos:      file_importer_proto_msgTypes,
	}.Build()
	File_importer_proto = out.File
	file_importer_proto_goTypes = nil
	file_importer_proto_depIdxs = nil
}
